version: '3'

services:
  app:
    image: 'final:latest'
    build:
      context: src/main/java/docker
    container_name: app
    ports:
      - "8090:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/phoenix"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "7212Hey)"

  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "7212Hey)"
      PGDATA : "/opt/homebrew/var/postgresql@14"
      POSTGRES_DB: "phoenix"
    ports:
      - "5432:5432"
volumes:
  db:
    driver: local